url: "https://deanattali.com/shinyjs"
baseurl: "/shinyjs"

title: shinyjs R package | by Dean Attali

# Short description of your site
description: Easily improve the user experience of your Shiny apps in seconds.

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Overview: overview
  Quick Start: basic
  Example: example
  Advanced: advanced
  Extend: extend
  Help: help

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Dean Attali
  email: "dean@attalitech.com"


# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-59820529-1"

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
